const data = [
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sit amet urna porttitor, dapibus sapien a, vestibulum felis. Praesent laoreet mollis ultrices. Donec nec fringilla arcu, blandit consequat purus. Aenean molestie sapien et facilisis iaculis. In ipsum leo, euismod eget ante vitae, aliquet accumsan justo. Curabitur venenatis facilisis condimentum. Quisque sagittis vehicula magna, in tempor dolor. Curabitur mattis ligula ac massa suscipit malesuada. Integer dapibus lectus sed velit maximus facilisis. Proin posuere tristique lectus, sit amet ornare odio ultricies at. Donec id sollicitudin nunc. Vestibulum cursus eget massa in volutpat. Sed eget sapien posuere nulla suscipit pretium. Morbi tristique consectetur mauris dapibus rutrum. Sed tempus faucibus rhoncus. Quisque nec justo sem.',

'Nunc sed pulvinar est. Nam euismod ipsum quis eros maximus sagittis. Nullam et est sed odio tincidunt posuere. Praesent in egestas quam. Morbi egestas nec mi nec posuere. Curabitur tincidunt orci non felis euismod, vitae blandit lectus vulputate. Vestibulum urna ipsum, tristique id nulla in, auctor tincidunt neque. Aenean blandit fringilla turpis eget posuere. Donec pretium consequat vulputate. Vestibulum ante dui, elementum vel ex a, maximus blandit lectus. Aliquam quis augue nec nisl efficitur vestibulum. Quisque dignissim felis at nibh sagittis, id interdum ante hendrerit.',

'Phasellus imperdiet dui at neque laoreet consequat. Nullam dui turpis, vulputate ac nisl quis, ultricies laoreet justo. Mauris cursus nulla libero, quis condimentum orci fermentum nec. Phasellus convallis massa metus, ut consequat nisl feugiat nec. In ut risus non ipsum consequat volutpat. Etiam tincidunt neque sapien, sit amet consectetur massa lobortis nec. Etiam quis justo non magna convallis viverra. Maecenas ullamcorper ipsum vel ultrices congue. Integer pulvinar dui at massa lacinia ullamcorper.',

'Donec bibendum mollis risus non pulvinar. Etiam ultricies, enim ut eleifend luctus, orci ipsum vulputate tellus, non volutpat mauris sem vitae justo. In lacus justo, finibus ac posuere nec, vehicula at quam. Mauris eget consectetur justo. Fusce vel faucibus enim. Pellentesque eget accumsan urna. Cras ullamcorper magna sapien, eu tincidunt arcu blandit ut. Aenean vestibulum elit non eleifend porta. Sed ut ornare tortor, at porta lectus. Integer consectetur urna eget feugiat gravida.',

'Vivamus ac dignissim dui, non pellentesque turpis. Ut placerat lacus nec mauris bibendum, nec sagittis est bibendum. Donec eu porttitor urna. Aenean viverra tortor non convallis pretium. Fusce pellentesque dignissim tristique. Praesent vehicula dapibus pretium. Donec tincidunt tortor purus, a interdum odio accumsan a. Vivamus a vestibulum est. Nulla et justo quis leo efficitur finibus a ac eros. Aenean ornare augue vitae neque blandit, quis efficitur dolor imperdiet.',

'Praesent non lacus congue, rutrum ante non, dictum leo. Donec rhoncus imperdiet augue, eget accumsan turpis faucibus ac. Sed aliquet metus sed est feugiat dignissim. Donec vel ante sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut consectetur est quis ipsum feugiat, ac euismod elit placerat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In elementum ex erat, sed varius enim maximus sit amet.',

'Donec euismod fermentum elit id accumsan. Nullam semper, tortor hendrerit luctus posuere, velit lectus porta sem, in sollicitudin eros mauris sed lorem. Sed id massa mollis, eleifend augue eget, gravida metus. Proin sollicitudin justo at purus semper lobortis. Cras ut hendrerit elit. Donec auctor neque vel molestie vestibulum. Duis nisl risus, ultricies et eleifend vel, mollis et nibh. Aliquam tristique bibendum quam, quis mollis nunc pretium a. Maecenas imperdiet velit non sagittis rutrum. Phasellus condimentum posuere lobortis. Phasellus scelerisque dictum dui eget mattis. Suspendisse auctor est quis dui pulvinar, quis vestibulum ipsum posuere. Maecenas a nisi eu tortor tincidunt pretium. Pellentesque ut commodo tellus. Sed ac justo non ligula auctor scelerisque at accumsan velit.',

'Duis justo turpis, sagittis eu tortor vitae, lacinia cursus erat. Etiam et sodales risus. Fusce eros odio, laoreet vitae semper eget, porta ac neque. Donec pellentesque orci eget felis molestie, id maximus purus sodales. Curabitur laoreet nisi ultrices, ullamcorper mi eget, rutrum erat. Integer lacinia maximus lectus eleifend ornare. In eu est eget mi ornare viverra non ac dui. Aenean at volutpat mauris.',

'In diam nulla, vestibulum et feugiat eget, efficitur at felis. Proin mi diam, convallis vel enim non, egestas interdum eros. Curabitur in bibendum lectus, aliquam condimentum lacus. Curabitur eget iaculis massa, ut viverra magna. Vivamus pulvinar ex ut dolor accumsan, sed imperdiet urna mollis. Vivamus imperdiet lacinia libero, non rhoncus ipsum imperdiet congue. Vestibulum eget est dui. Proin ullamcorper sem id lacinia laoreet. Nunc fringilla pharetra lorem non sodales. Morbi sit amet quam id odio dapibus iaculis. Aliquam sed elit ut ex pulvinar commodo. Mauris vehicula elit sed eros fringilla, ac ornare lorem lacinia. Nam et sapien ut sapien cursus pretium id eget lectus.',

'Nullam et interdum lacus. Ut ultrices pretium libero vel consectetur. Nam vitae mi et tellus varius scelerisque. Nam enim orci, efficitur ut semper at, vestibulum a mi. Curabitur non venenatis risus. Donec quis maximus tellus. Morbi quis diam a nibh sollicitudin gravida. Quisque in eros mi. Curabitur dignissim finibus nisi, consequat malesuada turpis placerat eget.'
]

export default data;